language: cpp

compiler: gcc

branches:
  only: master

before_install:
- autoreconf --install --force

notifications:
  recipients: igordeoliveirasa@gmail.com
  email:
    on_success: change
    on_failure: always
