language: cpp

compiler: gcc

branches:
  only: master

before_script:
- autoreconf --install --force

script:
- ./configure
- make check

notifications:
  recipients: igordeoliveirasa@gmail.com
  email:
    on_success: change
    on_failure: always
